# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', 'load_init_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=2),
        ),
    ]
