# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models

def load_Zuora(apps, schema_editor):
    User = apps.get_model("User")
    zuora = User(name = "Corporate", email = 'donations@zuora.com')
    zuora.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(load_Zuora),
    ]
