# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170713_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ('-votes', 'name')},
        ),
    ]
